<?php
/** Shared Accountant Management placeholder data for future MySQL integration. */
$accountantDepartments = ['Finance', 'Accounts', 'Bursary', 'Payroll'];
$accountantStatuses = ['Active', 'Inactive', 'On Leave', 'Suspended', 'Deleted'];
$accountantPermissions = ['Fee Management', 'Payment Collection', 'Receipt Management', 'Expense Management', 'Payroll', 'Financial Reports'];
$accountantRecords = [
    ['accountant_id'=>1,'passport'=>'../assets/img/user/user-05.jpg','staff_id'=>'ACC001','first_name'=>'John','middle_name'=>'','last_name'=>'Ibrahim','full_name'=>'John Ibrahim','gender'=>'Male','date_of_birth'=>'1988-06-15','nationality'=>'Nigerian','state'=>'Katsina','local_government'=>'Katsina','address'=>'Finance Quarters, Katsina','phone'=>'08034561234','email'=>'john.ibrahim@school.test','department'=>'Finance','designation'=>'Accountant','employment_date'=>'2019-09-02','status'=>'Active','qualification'=>'B.Sc Accounting','experience'=>7,'certification'=>'ICAN','payments_processed'=>4320,'receipts_generated'=>1850,'expenses_recorded'=>640,'payroll_processed'=>72,'financial_reports'=>285],
    ['accountant_id'=>2,'passport'=>'../assets/img/user/user-06.jpg','staff_id'=>'ACC002','first_name'=>'Maryam','middle_name'=>'','last_name'=>'Bala','full_name'=>'Maryam Bala','gender'=>'Female','date_of_birth'=>'1991-03-24','nationality'=>'Nigerian','state'=>'Katsina','local_government'=>'Daura','address'=>'Daura Road, Katsina','phone'=>'08123456789','email'=>'maryam.bala@school.test','department'=>'Bursary','designation'=>'Accountant','employment_date'=>'2021-01-12','status'=>'Active','qualification'=>'HND Accounting','experience'=>4,'certification'=>'ANAN','payments_processed'=>2890,'receipts_generated'=>1240,'expenses_recorded'=>310,'payroll_processed'=>36,'financial_reports'=>120],
    ['accountant_id'=>3,'passport'=>'../assets/img/user/user-07.jpg','staff_id'=>'ACC003','first_name'=>'Samuel','middle_name'=>'','last_name'=>'Ade','full_name'=>'Samuel Ade','gender'=>'Male','date_of_birth'=>'1985-11-01','nationality'=>'Nigerian','state'=>'Kaduna','local_government'=>'Zaria','address'=>'Staff Estate, Katsina','phone'=>'07061234567','email'=>'samuel.ade@school.test','department'=>'Payroll','designation'=>'Accountant','employment_date'=>'2018-04-18','status'=>'Inactive','qualification'=>'B.Sc Finance','experience'=>9,'certification'=>'ACCA','payments_processed'=>980,'receipts_generated'=>540,'expenses_recorded'=>440,'payroll_processed'=>95,'financial_reports'=>88],
];
function sms_admin_accountant_selected_id(): int { return (int) ($_GET['accountant_id'] ?? $_POST['accountant_id'] ?? 1); }
function sms_admin_accountant_find(array $records, ?int $id): array { foreach ($records as $record) { if ((int)$record['accountant_id'] === (int)$id) { return $record; } } return $records[0]; }
?>