<?php require_once('includes/header.php'); ?>
<?php require_once('includes/academic-data.php'); ?>
<?php require_once('includes/academic-module-styles.php'); ?>
<?php
/**
 * Centralized Academic Management page.
 * Future MySQL integration should replace these arrays with repositories and CRUD controllers per section.
 */
function sms_academic_count_local(array $items, string $field, string $value): int { return count(array_filter($items, fn($item) => (string)($item[$field] ?? '') === $value)); }
function sms_academic_cards_local(array $cards): void { echo '<section class="row g-3 mb-4">'; foreach ($cards as $card) { echo '<div class="col-sm-6 col-xl-2">'; sms_render_component('statistics-card', $card); echo '</div>'; } echo '</section>'; }
function sms_academic_badge_local(string $status): string { return '<span class="status-badge">' . sms_e($status) . '</span>'; }
$sections = [
    ['id' => 'sessions', 'label' => 'Academic Sessions', 'icon' => 'fa-calendar-days'],
    ['id' => 'terms', 'label' => 'Terms', 'icon' => 'fa-calendar-week'],
    ['id' => 'classes', 'label' => 'Classes', 'icon' => 'fa-school'],
    ['id' => 'sections', 'label' => 'Sections / Arms', 'icon' => 'fa-layer-group'],
    ['id' => 'departments', 'label' => 'Departments', 'icon' => 'fa-building-columns'],
    ['id' => 'subjects', 'label' => 'Subjects', 'icon' => 'fa-book-open'],
    ['id' => 'calendar', 'label' => 'School Calendar', 'icon' => 'fa-calendar-check'],
];
$activeSession = current(array_filter($academicSessions, fn($item) => $item['status'] === 'Active')) ?: $academicSessions[0];
$activeTerm = current(array_filter($academicTerms, fn($item) => $item['status'] === 'Active')) ?: $academicTerms[0];
$cards = [
    ['title' => 'Active Session', 'value' => $activeSession['name'], 'description' => 'Current academic session', 'icon' => 'fa-calendar-days', 'color' => 'success'],
    ['title' => 'Current Term', 'value' => $activeTerm['name'], 'description' => 'Active term', 'icon' => 'fa-calendar-week', 'color' => 'blue'],
    ['title' => 'Total Classes', 'value' => count($academicClasses), 'description' => 'Configured classes', 'icon' => 'fa-school', 'color' => 'success'],
    ['title' => 'Total Subjects', 'value' => count($academicSubjects), 'description' => 'Academic subjects', 'icon' => 'fa-book-open', 'color' => 'warning'],
    ['title' => 'Departments', 'value' => count($academicDepartments), 'description' => 'Academic units', 'icon' => 'fa-building-columns', 'color' => 'success'],
    ['title' => 'Upcoming Events', 'value' => sms_academic_count_local($schoolEvents, 'status', 'Upcoming'), 'description' => 'Calendar events', 'icon' => 'fa-calendar-check', 'color' => 'blue'],
];
?>
<style>
.admin-academic-module .academic-shell{display:grid;grid-template-columns:280px minmax(0,1fr);gap:22px}.admin-academic-module .academic-nav{position:sticky;top:90px;align-self:start}.admin-academic-module .academic-nav button{width:100%;border:0;border-radius:16px;background:#f8fafc;color:var(--am-ink);padding:14px 15px;margin-bottom:10px;display:flex;align-items:center;gap:10px;font-weight:900;text-align:left;transition:.18s}.admin-academic-module .academic-nav button.active,.admin-academic-module .academic-nav button:hover{background:var(--am-primary);color:#fff;box-shadow:0 12px 24px rgba(15,118,110,.2)}.admin-academic-module .academic-panel{display:none}.admin-academic-module .academic-panel.active{display:block}.admin-academic-module .mobile-academic-select{display:none;margin-bottom:16px}.admin-academic-module .bulk-row{display:flex;flex-wrap:wrap;gap:8px}.admin-academic-module .class-chip{display:inline-flex;padding:6px 10px;border-radius:999px;background:var(--am-soft);color:var(--am-dark);font-size:12px;font-weight:900;margin:2px}@media(max-width:991.98px){.admin-academic-module .academic-shell{grid-template-columns:1fr}.admin-academic-module .academic-nav{display:none}.admin-academic-module .mobile-academic-select{display:block}}
</style>
<div class="admin-academic-module">
    <section class="module-hero"><div class="breadcrumb-line">Dashboard <i class="fa-solid fa-angle-right mx-1"></i> Academic Management</div><div class="d-flex align-items-center justify-content-between flex-wrap gap-3"><div><span class="module-kicker"><i class="fa-solid fa-school-flag"></i> Academic Management</span><h3 class="mt-3 mb-2">Academic Management</h3><p class="text-muted mb-0">Manage sessions, terms, classes, sections, departments, subjects, and school calendar from one centralized page.</p></div><button class="module-btn btn-primary-soft" data-bs-toggle="modal" data-bs-target="#academicFormModal" type="button"><i class="fa-solid fa-plus"></i> Add Record</button></div></section>
    <?php sms_academic_cards_local($cards); ?>
    <section class="module-card"><div class="d-flex justify-content-between align-items-center flex-wrap gap-3"><div><h4 class="mb-1">Global Search</h4><p class="text-muted mb-0">Search within the currently selected academic section.</p></div><div class="d-flex gap-2 flex-wrap"><input class="form-control" id="academicSearch" style="min-width:260px" placeholder="Search current section"><button class="module-btn btn-muted-soft" id="clearAcademicSearch" type="button">Clear</button></div></div></section>
    <div class="academic-shell">
        <aside class="module-card academic-nav" aria-label="Academic Management sections"><?php foreach ($sections as $index => $section): ?><button class="academic-tab <?php echo $index === 0 ? 'active' : ''; ?>" data-target="<?php echo sms_e($section['id']); ?>" type="button"><i class="fa-solid <?php echo sms_e($section['icon']); ?>"></i> <?php echo sms_e($section['label']); ?></button><?php endforeach; ?></aside>
        <main>
            <select class="form-select mobile-academic-select" id="mobileAcademicSelect"><?php foreach ($sections as $section): ?><option value="<?php echo sms_e($section['id']); ?>"><?php echo sms_e($section['label']); ?></option><?php endforeach; ?></select>
            <section class="academic-panel active" id="sessions"><div class="module-card"><div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3"><div><h4>Academic Sessions</h4><p class="text-muted mb-0">Only one session can be active at a time.</p></div><div class="bulk-row"><button class="module-btn btn-primary-soft add-record" data-entity="Academic Session" data-bs-toggle="modal" data-bs-target="#academicFormModal" type="button">Add Session</button><button class="module-btn btn-outline-soft export-record" data-format="CSV" type="button">Export CSV</button><button class="module-btn btn-outline-soft export-record" data-format="Excel" type="button">Export Excel</button><button class="module-btn btn-muted-soft" onclick="window.print()" type="button">Print</button></div></div><div class="table-shell"><table class="table academic-table"><thead><tr><th><input class="form-check-input" type="checkbox"></th><th>Session Name</th><th>Start Date</th><th>End Date</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($academicSessions as $item): ?><tr><td><input class="form-check-input" type="checkbox"></td><td><?php echo sms_e($item['name']); ?></td><td><?php echo sms_e($item['start_date']); ?></td><td><?php echo sms_e($item['end_date']); ?></td><td><?php echo sms_academic_badge_local($item['status']); ?></td><td><button class="action-btn edit-record" data-entity="Academic Session" data-bs-toggle="modal" data-bs-target="#academicFormModal"><i class="fa-solid fa-pen"></i></button><button class="action-btn activate-record" title="Activate"><i class="fa-solid fa-circle-check"></i></button><button class="action-btn delete-record" data-name="<?php echo sms_e($item['name']); ?>" data-bs-toggle="modal" data-bs-target="#deleteAcademicModal"><i class="fa-solid fa-trash"></i></button></td></tr><?php endforeach; ?></tbody></table></div></div></section>
            <section class="academic-panel" id="terms"><div class="module-card"><div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3"><div><h4>Terms</h4><p class="text-muted mb-0">Only one term can be active within the active session.</p></div><div class="bulk-row"><button class="module-btn btn-primary-soft add-record" data-entity="Term" data-bs-toggle="modal" data-bs-target="#academicFormModal" type="button">Add Term</button><button class="module-btn btn-danger-soft bulk-delete" type="button">Delete Selected</button><button class="module-btn btn-outline-soft export-record" data-format="CSV" type="button">Export CSV</button><button class="module-btn btn-muted-soft" onclick="window.print()" type="button">Print</button></div></div><div class="table-shell"><table class="table academic-table"><thead><tr><th><input class="form-check-input" type="checkbox"></th><th>Academic Session</th><th>Term</th><th>Start Date</th><th>End Date</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($academicTerms as $item): ?><tr><td><input class="form-check-input" type="checkbox"></td><td><?php echo sms_e($item['session']); ?></td><td><?php echo sms_e($item['name']); ?></td><td><?php echo sms_e($item['start_date']); ?></td><td><?php echo sms_e($item['end_date']); ?></td><td><?php echo sms_academic_badge_local($item['status']); ?></td><td><button class="action-btn edit-record" data-entity="Term" data-bs-toggle="modal" data-bs-target="#academicFormModal"><i class="fa-solid fa-pen"></i></button><button class="action-btn activate-record"><i class="fa-solid fa-circle-check"></i></button><button class="action-btn delete-record" data-name="<?php echo sms_e($item['name']); ?>" data-bs-toggle="modal" data-bs-target="#deleteAcademicModal"><i class="fa-solid fa-trash"></i></button></td></tr><?php endforeach; ?></tbody></table></div></div></section>
            <section class="academic-panel" id="classes"><div class="module-card"><div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3"><div><h4>Classes</h4><p class="text-muted mb-0">Manage junior and senior school class levels.</p></div><div class="bulk-row"><button class="module-btn btn-primary-soft add-record" data-entity="Class" data-bs-toggle="modal" data-bs-target="#academicFormModal" type="button">Add Class</button><button class="module-btn btn-outline-soft export-record" data-format="Excel" type="button">Export Excel</button><button class="module-btn btn-muted-soft" onclick="window.print()" type="button">Print</button></div></div><div class="table-shell"><table class="table academic-table"><thead><tr><th>Class Name</th><th>Level</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($academicClasses as $item): ?><tr><td><?php echo sms_e($item['name']); ?></td><td><?php echo sms_e($item['level']); ?></td><td><?php echo sms_academic_badge_local($item['status']); ?></td><td><button class="action-btn edit-record" data-entity="Class" data-bs-toggle="modal" data-bs-target="#academicFormModal"><i class="fa-solid fa-pen"></i></button><button class="action-btn delete-record" data-name="<?php echo sms_e($item['name']); ?>" data-bs-toggle="modal" data-bs-target="#deleteAcademicModal"><i class="fa-solid fa-trash"></i></button></td></tr><?php endforeach; ?></tbody></table></div></div></section>
            <section class="academic-panel" id="sections"><div class="module-card"><div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3"><div><h4>Sections / Arms</h4><p class="text-muted mb-0">Manage class arms and capacities.</p></div><button class="module-btn btn-primary-soft add-record" data-entity="Section" data-bs-toggle="modal" data-bs-target="#academicFormModal" type="button">Add Section</button></div><div class="table-shell"><table class="table academic-table"><thead><tr><th>Class</th><th>Section</th><th>Capacity</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($academicSections as $item): ?><tr><td><?php echo sms_e($item['class']); ?></td><td><?php echo sms_e($item['name']); ?></td><td><?php echo sms_e($item['capacity']); ?></td><td><?php echo sms_academic_badge_local($item['status']); ?></td><td><button class="action-btn edit-record" data-entity="Section" data-bs-toggle="modal" data-bs-target="#academicFormModal"><i class="fa-solid fa-pen"></i></button><button class="action-btn delete-record" data-name="<?php echo sms_e($item['name']); ?>" data-bs-toggle="modal" data-bs-target="#deleteAcademicModal"><i class="fa-solid fa-trash"></i></button></td></tr><?php endforeach; ?></tbody></table></div></div></section>
            <section class="academic-panel" id="departments"><div class="module-card"><div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3"><div><h4>Departments</h4><p class="text-muted mb-0">Manage academic departments and descriptions.</p></div><button class="module-btn btn-primary-soft add-record" data-entity="Department" data-bs-toggle="modal" data-bs-target="#academicFormModal" type="button">Add Department</button></div><div class="table-shell"><table class="table academic-table"><thead><tr><th>Department</th><th>Description</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($academicDepartments as $item): ?><tr><td><?php echo sms_e($item['name']); ?></td><td><?php echo sms_e($item['description']); ?></td><td><?php echo sms_academic_badge_local($item['status']); ?></td><td><button class="action-btn edit-record" data-entity="Department" data-bs-toggle="modal" data-bs-target="#academicFormModal"><i class="fa-solid fa-pen"></i></button><button class="action-btn delete-record" data-name="<?php echo sms_e($item['name']); ?>" data-bs-toggle="modal" data-bs-target="#deleteAcademicModal"><i class="fa-solid fa-trash"></i></button></td></tr><?php endforeach; ?></tbody></table></div></div></section>
            <section class="academic-panel" id="subjects"><div class="module-card"><div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3"><div><h4>Subjects</h4><p class="text-muted mb-0">Assign subjects to multiple classes with a future searchable multi-select.</p></div><button class="module-btn btn-primary-soft add-record" data-entity="Subject" data-bs-toggle="modal" data-bs-target="#academicFormModal" type="button">Add Subject</button></div><div class="table-shell"><table class="table academic-table"><thead><tr><th>Subject Code</th><th>Subject Name</th><th>Department</th><th>Applicable Classes</th><th>Subject Type</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($academicSubjects as $item): ?><tr><td><?php echo sms_e($item['code']); ?></td><td><?php echo sms_e($item['name']); ?></td><td><?php echo sms_e($item['department']); ?></td><td><?php foreach (explode(',', $item['level']) as $level): ?><span class="class-chip"><?php echo sms_e(trim($level)); ?></span><?php endforeach; ?></td><td><?php echo sms_e($item['type']); ?></td><td><?php echo sms_academic_badge_local($item['status']); ?></td><td><button class="action-btn edit-record" data-entity="Subject" data-bs-toggle="modal" data-bs-target="#academicFormModal"><i class="fa-solid fa-pen"></i></button><button class="action-btn delete-record" data-name="<?php echo sms_e($item['name']); ?>" data-bs-toggle="modal" data-bs-target="#deleteAcademicModal"><i class="fa-solid fa-trash"></i></button></td></tr><?php endforeach; ?></tbody></table></div></div></section>
            <section class="academic-panel" id="calendar"><div class="module-card"><div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3"><div><h4>School Calendar</h4><p class="text-muted mb-0">Manage academic events, examinations, meetings, holidays, and activities.</p></div><button class="module-btn btn-primary-soft add-record" data-entity="Calendar Event" data-bs-toggle="modal" data-bs-target="#academicFormModal" type="button">Add Event</button></div><div class="table-shell"><table class="table academic-table"><thead><tr><th>Event Title</th><th>Event Type</th><th>Start Date</th><th>End Date</th><th>Location</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($schoolEvents as $item): ?><tr><td><?php echo sms_e($item['title']); ?></td><td><?php echo sms_e($item['type']); ?></td><td><?php echo sms_e($item['start_date']); ?></td><td><?php echo sms_e($item['end_date']); ?></td><td><?php echo sms_e($item['location']); ?></td><td><?php echo sms_academic_badge_local($item['status']); ?></td><td><button class="action-btn edit-record" data-entity="Calendar Event" data-bs-toggle="modal" data-bs-target="#academicFormModal"><i class="fa-solid fa-pen"></i></button><button class="action-btn delete-record" data-name="<?php echo sms_e($item['title']); ?>" data-bs-toggle="modal" data-bs-target="#deleteAcademicModal"><i class="fa-solid fa-trash"></i></button></td></tr><?php endforeach; ?></tbody></table></div></div></section>
        </main>
    </div>
    <div class="modal fade" id="academicFormModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered modal-lg"><form class="modal-content" id="academicEntityForm" method="post" action="academic-management-save.php"><div class="modal-header"><h5 class="modal-title" id="academicModalTitle">Add / Edit Academic Record</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><p class="text-muted fw-bold">Future backend logic should validate role permissions, save only the selected entity, and write audit logs.</p><input type="hidden" name="entity" id="academicEntityType"><div class="form-grid"><div><label>Name / Title</label><input class="form-control" name="name" required></div><div><label>Status</label><select class="form-select" name="status"><?php foreach ($academicStatuses as $status): ?><option><?php echo sms_e($status); ?></option><?php endforeach; ?></select></div><div><label>Start Date</label><input class="form-control" type="date" name="start_date"></div><div><label>End Date</label><input class="form-control" type="date" name="end_date"></div><div><label>Class / Department</label><input class="form-control" name="group" placeholder="Optional future relation ID"></div><div><label>Subject Type / Level</label><input class="form-control" name="type" placeholder="Optional"></div><div class="full"><label>Applicable Classes / Description</label><textarea class="form-control" name="description" placeholder="Use future searchable multi-select for subjects/classes"></textarea></div></div></div><div class="modal-footer"><button class="module-btn btn-muted-soft" type="reset">Reset</button><button class="module-btn btn-muted-soft" type="button" data-bs-dismiss="modal">Cancel</button><button class="module-btn btn-primary-soft" type="submit">Save Record</button></div></form></div></div>
    <div class="modal fade" id="deleteAcademicModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" id="deleteAcademicForm" method="post" action="academic-management-delete.php"><div class="modal-header"><h5 class="modal-title">Delete Record</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><p>Are you sure you want to delete this academic record?</p><p class="text-muted fw-bold">This should become a permission-protected soft delete with audit logging.</p><strong id="deleteRecordName">Selected record</strong></div><div class="modal-footer"><button class="module-btn btn-muted-soft" type="button" data-bs-dismiss="modal">Cancel</button><button class="module-btn btn-danger-soft" type="submit">Delete</button></div></form></div></div>
</div></div></div>
<script>
/* Centralized Academic Management behavior: section navigation, search, modals, and placeholders. */
(function(){
    function activate(target){document.querySelectorAll('.academic-tab').forEach(function(tab){tab.classList.toggle('active',tab.dataset.target===target);});document.querySelectorAll('.academic-panel').forEach(function(panel){panel.classList.toggle('active',panel.id===target);});var mobile=document.getElementById('mobileAcademicSelect');if(mobile){mobile.value=target;}filterRows();}
    document.querySelectorAll('.academic-tab').forEach(function(tab){tab.addEventListener('click',function(){activate(tab.dataset.target);});});
    var mobile=document.getElementById('mobileAcademicSelect');if(mobile){mobile.addEventListener('change',function(){activate(mobile.value);});}
    function currentPanel(){return document.querySelector('.academic-panel.active');}
    function filterRows(){var q=(document.getElementById('academicSearch').value||'').toLowerCase();var panel=currentPanel();if(!panel){return;}panel.querySelectorAll('tbody tr').forEach(function(row){row.style.display=!q||row.textContent.toLowerCase().indexOf(q)>-1?'':'none';});}
    document.getElementById('academicSearch').addEventListener('input',filterRows);document.getElementById('clearAcademicSearch').addEventListener('click',function(){document.getElementById('academicSearch').value='';filterRows();});
    document.querySelectorAll('.add-record,.edit-record').forEach(function(button){button.addEventListener('click',function(){var entity=button.dataset.entity||'Academic Record';document.getElementById('academicModalTitle').textContent='Add / Edit '+entity;document.getElementById('academicEntityType').value=entity;});});
    document.querySelectorAll('.delete-record').forEach(function(button){button.addEventListener('click',function(){document.getElementById('deleteRecordName').textContent=button.dataset.name||'Selected record';});});
    document.querySelectorAll('.activate-record').forEach(function(button){button.addEventListener('click',function(){alert('Activation placeholder: backend should enforce one active session and one active term in the active session.');});});
    document.querySelectorAll('.export-record').forEach(function(button){button.addEventListener('click',function(){alert(button.dataset.format+' export placeholder ready for backend integration.');});});
    document.querySelectorAll('.bulk-delete').forEach(function(button){button.addEventListener('click',function(){alert('Bulk delete placeholder. Future backend should soft-delete selected records with audit logs.');});});
    document.getElementById('academicEntityForm').addEventListener('submit',function(e){e.preventDefault();if(!this.checkValidity()){this.reportValidity();return;}alert('Record saved in placeholder mode. Future endpoint: '+this.action);});
    document.getElementById('deleteAcademicForm').addEventListener('submit',function(e){e.preventDefault();alert('Record deleted in placeholder mode. Future endpoint: '+this.action);});
})();
</script>
<?php require_once('includes/footer.php'); ?>