<?php require_once('includes/header.php'); ?>
<?php require_once('includes/attendance-module-styles.php'); ?>
<?php
/**
 * Placeholder audit log records.
 * Future MySQL integration should load these from a centralized audit_logs table.
 */
$auditLogs = [
    ['id' => 1, 'created_at' => '2026-07-03 08:12 AM', 'user' => 'Administrator', 'role' => 'Admin', 'module' => 'Students', 'action' => 'Create', 'description' => 'Created student record REG-2026-001.', 'record_id' => 'student:1', 'ip' => '192.168.1.12', 'browser' => 'Chrome 126', 'os' => 'Windows 11', 'device' => 'Desktop', 'session_id' => 'SES-ADM-0001', 'status' => 'Success'],
    ['id' => 2, 'created_at' => '2026-07-03 08:40 AM', 'user' => 'John Musa', 'role' => 'Teacher', 'module' => 'Results', 'action' => 'Update', 'description' => 'Updated Mathematics result draft for SS 2 Science.', 'record_id' => 'result_batch:12', 'ip' => '192.168.1.22', 'browser' => 'Edge 126', 'os' => 'Windows 10', 'device' => 'Laptop', 'session_id' => 'SES-TCH-0041', 'status' => 'Success'],
    ['id' => 3, 'created_at' => '2026-07-03 09:05 AM', 'user' => 'Unknown User', 'role' => 'Guest', 'module' => 'Users', 'action' => 'Login', 'description' => 'Failed login attempt for accountant account ACC001.', 'record_id' => 'user:ACC001', 'ip' => '102.88.42.11', 'browser' => 'Firefox 127', 'os' => 'Android', 'device' => 'Mobile', 'session_id' => 'N/A', 'status' => 'Failed'],
    ['id' => 4, 'created_at' => '2026-07-03 09:30 AM', 'user' => 'Grace Audu', 'role' => 'Teacher', 'module' => 'CBT', 'action' => 'Publish', 'description' => 'Published JSS 1 English Language CBT.', 'record_id' => 'cbt_exam:2', 'ip' => '192.168.1.31', 'browser' => 'Chrome 126', 'os' => 'Windows 11', 'device' => 'Desktop', 'session_id' => 'SES-TCH-0087', 'status' => 'Success'],
    ['id' => 5, 'created_at' => '2026-07-03 10:10 AM', 'user' => 'John Ibrahim', 'role' => 'Accountant', 'module' => 'Finance', 'action' => 'Export', 'description' => 'Exported outstanding fees report as PDF.', 'record_id' => 'report:finance-outstanding', 'ip' => '192.168.1.44', 'browser' => 'Chrome 126', 'os' => 'Windows 11', 'device' => 'Desktop', 'session_id' => 'SES-ACC-0020', 'status' => 'Warning'],
    ['id' => 6, 'created_at' => '2026-07-03 11:15 AM', 'user' => 'Administrator', 'role' => 'Admin', 'module' => 'Timetable', 'action' => 'Lock', 'description' => 'Locked published SS 2 Science timetable.', 'record_id' => 'timetable:4', 'ip' => '192.168.1.12', 'browser' => 'Chrome 126', 'os' => 'Windows 11', 'device' => 'Desktop', 'session_id' => 'SES-ADM-0001', 'status' => 'Success'],
];
$roles = ['Admin', 'Teacher', 'Accountant', 'Student', 'Parent', 'Guest'];
$modules = ['Students', 'Teachers', 'Accountants', 'Academic Management', 'Attendance', 'Results', 'CBT', 'Timetable', 'Finance', 'Users', 'Settings'];
$actions = ['Login', 'Logout', 'Create', 'Update', 'Delete', 'Approve', 'Publish', 'Lock', 'Unlock', 'Export', 'Import', 'Password Change', 'Profile Update', 'System Settings'];
$statuses = ['Success', 'Failed', 'Warning'];
$total = count($auditLogs);
$today = count(array_filter($auditLogs, fn($log) => str_starts_with($log['created_at'], '2026-07-03')));
$failed = count(array_filter($auditLogs, fn($log) => $log['status'] === 'Failed' && $log['action'] === 'Login'));
$activeUsers = count(array_unique(array_column($auditLogs, 'user')));
function sms_audit_status_class(string $status): string { return 'status-' . strtolower($status); }
function sms_audit_badge(string $status): string { return '<span class="status-badge ' . sms_e(sms_audit_status_class($status)) . '"><i class="fa-solid fa-circle"></i> ' . sms_e($status) . '</span>'; }
function sms_audit_cards(array $cards): void { echo '<section class="row g-3 mb-4">'; foreach ($cards as $card) { echo '<div class="col-sm-6 col-xl-3">'; sms_render_component('statistics-card', $card); echo '</div>'; } echo '</section>'; }
$cards = [
    ['title' => 'Total Activities', 'value' => $total, 'description' => 'All tracked activities', 'icon' => 'fa-list-check', 'color' => 'success'],
    ['title' => "Today's Activities", 'value' => $today, 'description' => 'Activities recorded today', 'icon' => 'fa-calendar-day', 'color' => 'blue'],
    ['title' => 'Failed Login Attempts', 'value' => $failed, 'description' => 'Security events to review', 'icon' => 'fa-triangle-exclamation', 'color' => 'danger'],
    ['title' => 'Active Users', 'value' => $activeUsers, 'description' => 'Users seen in logs', 'icon' => 'fa-users', 'color' => 'warning'],
];
?>
<style>
.admin-audit-module .status-success{background:rgba(22,163,74,.12);color:#15803d}.admin-audit-module .status-failed{background:rgba(220,38,38,.1);color:#b91c1c}.admin-audit-module .status-warning{background:rgba(245,158,11,.14);color:#b45309}.admin-audit-module .audit-toggle{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:16px}.admin-audit-module .audit-toggle button{border:1px solid var(--at-border);background:#fff;color:var(--at-dark);border-radius:999px;padding:10px 15px;font-weight:900}.admin-audit-module .audit-toggle button.active{background:var(--at-primary);color:#fff}.admin-audit-module .timeline{position:relative;padding-left:24px}.admin-audit-module .timeline:before{content:"";position:absolute;left:9px;top:0;bottom:0;width:2px;background:rgba(15,118,110,.22)}.admin-audit-module .timeline-item{position:relative;padding:0 0 18px 20px}.admin-audit-module .timeline-item:before{content:"";position:absolute;left:-20px;top:4px;width:18px;height:18px;border-radius:50%;background:#0f766e;border:4px solid #d1fae5}.admin-audit-module .timeline-card{border:1px solid rgba(15,118,110,.16);border-radius:18px;padding:16px;background:#fff;box-shadow:0 12px 30px rgba(15,23,42,.06)}.admin-audit-module .empty-state{display:none;text-align:center;padding:42px;border:1px dashed rgba(15,118,110,.25);border-radius:22px;background:#f8fafc}.admin-audit-module .empty-state i{font-size:44px;color:#0f766e;margin-bottom:12px}
</style>
<div class="admin-attendance-module admin-audit-module">
    <section class="module-hero"><div class="breadcrumb-line">Dashboard <i class="fa-solid fa-angle-right mx-1"></i> Audit Logs</div><div class="d-flex align-items-center justify-content-between flex-wrap gap-3"><div><span class="module-kicker"><i class="fa-solid fa-shield-halved"></i> Audit Logs</span><h3 class="mt-3 mb-2">Audit Logs</h3><p class="text-muted mb-0">Monitor user activity across the School Management System for security, accountability, and troubleshooting.</p></div><button class="module-btn btn-outline-soft" type="button" onclick="window.print()"><i class="fa-solid fa-print"></i> Print</button></div></section>
    <?php sms_audit_cards($cards); ?>
    <section class="module-card"><h4>Search & Filter</h4><form id="auditFilterForm"><div class="filter-grid"><div><label>Date From</label><input class="form-control" type="date"></div><div><label>Date To</label><input class="form-control" type="date"></div><div><label>User Role</label><select class="form-select" id="roleFilter"><option value="">All Roles</option><?php foreach ($roles as $role): ?><option><?php echo sms_e($role); ?></option><?php endforeach; ?></select></div><div><label>User</label><input class="form-control" id="userFilter" placeholder="Search user"></div><div><label>Module</label><select class="form-select" id="moduleFilter"><option value="">All Modules</option><?php foreach ($modules as $module): ?><option><?php echo sms_e($module); ?></option><?php endforeach; ?></select></div><div><label>Action Type</label><select class="form-select" id="actionFilter"><option value="">All Actions</option><?php foreach ($actions as $action): ?><option><?php echo sms_e($action); ?></option><?php endforeach; ?></select></div><div><label>Status</label><select class="form-select" id="statusFilter"><option value="">All Statuses</option><?php foreach ($statuses as $status): ?><option><?php echo sms_e($status); ?></option><?php endforeach; ?></select></div><div class="d-flex align-items-end gap-2"><button class="module-btn btn-primary-soft" type="submit"><i class="fa-solid fa-search"></i> Search</button><button class="module-btn btn-muted-soft" type="reset">Reset Filters</button></div></div></form></section>
    <section class="module-card"><div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3"><div><h4 class="mb-1">Audit Trail</h4><p class="text-muted mb-0">Audit logs are read-only. No edit or delete actions are available.</p></div><div class="d-flex flex-wrap gap-2"><button class="module-btn btn-outline-soft audit-export" data-format="PDF" type="button"><i class="fa-solid fa-file-pdf"></i> Export PDF</button><button class="module-btn btn-outline-soft audit-export" data-format="Excel" type="button"><i class="fa-solid fa-file-excel"></i> Export Excel</button><button class="module-btn btn-outline-soft audit-export" data-format="CSV" type="button"><i class="fa-solid fa-file-csv"></i> Export CSV</button><button class="module-btn btn-muted-soft" onclick="window.print()" type="button"><i class="fa-solid fa-print"></i> Print</button></div></div><div class="audit-toggle"><button class="active" data-view="table" type="button"><i class="fa-solid fa-table-list"></i> Table View</button><button data-view="timeline" type="button"><i class="fa-solid fa-timeline"></i> Timeline View</button></div>
        <div class="empty-state" id="auditEmptyState"><i class="fa-solid fa-folder-open"></i><h4>No audit logs found for the selected filters.</h4><p class="text-muted mb-0">Try adjusting your search or clearing filters.</p></div>
        <div id="auditTableView"><div class="table-shell"><table class="table" id="auditTable"><thead><tr><th>Date & Time</th><th>User</th><th>Role</th><th>Module</th><th>Action</th><th>Description</th><th>IP Address</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($auditLogs as $log): ?><tr data-role="<?php echo sms_e($log['role']); ?>" data-module="<?php echo sms_e($log['module']); ?>" data-action="<?php echo sms_e($log['action']); ?>" data-status="<?php echo sms_e($log['status']); ?>" data-search="<?php echo sms_e(strtolower($log['user'] . ' ' . $log['description'])); ?>"><td><?php echo sms_e($log['created_at']); ?></td><td><?php echo sms_e($log['user']); ?></td><td><?php echo sms_e($log['role']); ?></td><td><?php echo sms_e($log['module']); ?></td><td><?php echo sms_e($log['action']); ?></td><td><?php echo sms_e($log['description']); ?></td><td><?php echo sms_e($log['ip']); ?></td><td><?php echo sms_audit_badge($log['status']); ?></td><td><button class="action-btn audit-details" data-bs-toggle="modal" data-bs-target="#auditDetailsModal" data-log='<?php echo sms_e(json_encode($log)); ?>' title="View Details"><i class="fa-solid fa-eye"></i></button></td></tr><?php endforeach; ?></tbody></table></div></div>
        <div id="auditTimelineView" style="display:none"><div class="timeline"><?php foreach ($auditLogs as $log): ?><div class="timeline-item" data-role="<?php echo sms_e($log['role']); ?>" data-module="<?php echo sms_e($log['module']); ?>" data-action="<?php echo sms_e($log['action']); ?>" data-status="<?php echo sms_e($log['status']); ?>" data-search="<?php echo sms_e(strtolower($log['user'] . ' ' . $log['description'])); ?>"><div class="timeline-card"><div class="d-flex justify-content-between flex-wrap gap-2"><strong><?php echo sms_e($log['action']); ?> - <?php echo sms_e($log['module']); ?></strong><?php echo sms_audit_badge($log['status']); ?></div><p class="mb-1 mt-2"><?php echo sms_e($log['description']); ?></p><small class="text-muted"><?php echo sms_e($log['created_at']); ?> by <?php echo sms_e($log['user']); ?> (<?php echo sms_e($log['role']); ?>)</small></div></div><?php endforeach; ?></div></div>
        <div class="d-flex justify-content-between align-items-center flex-wrap gap-2 pt-3"><div class="d-flex align-items-center gap-2"><span class="text-muted fw-bold">Records per page</span><select class="form-select" style="width:90px"><option>10</option><option>25</option><option>50</option><option>100</option></select></div><div class="d-flex gap-2"><a class="module-btn btn-muted-soft" href="#">Previous</a><a class="module-btn btn-primary-soft" href="#">1</a><a class="module-btn btn-muted-soft" href="#">Next</a></div></div>
    </section>
    <div class="modal fade" id="auditDetailsModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Audit Log Details</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="form-grid"><div><label>User Name</label><input class="form-control" id="auditUser" readonly></div><div><label>User Role</label><input class="form-control" id="auditRole" readonly></div><div><label>Date & Time</label><input class="form-control" id="auditDate" readonly></div><div><label>Module</label><input class="form-control" id="auditModule" readonly></div><div><label>Action</label><input class="form-control" id="auditAction" readonly></div><div><label>IP Address</label><input class="form-control" id="auditIp" readonly></div><div><label>Browser</label><input class="form-control" id="auditBrowser" readonly></div><div><label>Operating System</label><input class="form-control" id="auditOs" readonly></div><div><label>Device Type</label><input class="form-control" id="auditDevice" readonly></div><div><label>Session ID</label><input class="form-control" id="auditSession" readonly></div><div><label>Status</label><input class="form-control" id="auditStatus" readonly></div><div class="full"><label>Detailed Description</label><textarea class="form-control" id="auditDescription" readonly></textarea></div></div></div><div class="modal-footer"><button class="module-btn btn-muted-soft" type="button" data-bs-dismiss="modal">Close</button></div></div></div></div>
</div></div></div>
<script>
/* Audit Logs frontend behavior: read-only details, filters, view toggle, exports, and empty state. */
(function(){
    var tableView=document.getElementById('auditTableView'), timelineView=document.getElementById('auditTimelineView'), empty=document.getElementById('auditEmptyState');
    document.querySelectorAll('.audit-toggle button').forEach(function(button){button.addEventListener('click',function(){document.querySelectorAll('.audit-toggle button').forEach(function(b){b.classList.remove('active')});button.classList.add('active');tableView.style.display=button.dataset.view==='table'?'':'none';timelineView.style.display=button.dataset.view==='timeline'?'':'none';});});
    function applyFilters(){var role=roleFilter.value,module=moduleFilter.value,action=actionFilter.value,status=statusFilter.value,user=userFilter.value.toLowerCase(),visible=0;document.querySelectorAll('#auditTable tbody tr,.timeline-item').forEach(function(row){var ok=(!role||row.dataset.role===role)&&(!module||row.dataset.module===module)&&(!action||row.dataset.action===action)&&(!status||row.dataset.status===status)&&(!user||row.dataset.search.indexOf(user)>-1);row.style.display=ok?'':'none';if(ok&&row.tagName==='TR'){visible++;}});empty.style.display=visible?'none':'block';}
    auditFilterForm.addEventListener('submit',function(e){e.preventDefault();applyFilters();});auditFilterForm.addEventListener('reset',function(){setTimeout(function(){document.querySelectorAll('#auditTable tbody tr,.timeline-item').forEach(function(row){row.style.display='';});empty.style.display='none';},0);});
    document.querySelectorAll('.audit-export').forEach(function(button){button.addEventListener('click',function(){alert(button.dataset.format+' export placeholder ready for future backend integration.');});});
    document.querySelectorAll('.audit-details').forEach(function(button){button.addEventListener('click',function(){var log=JSON.parse(button.dataset.log);auditUser.value=log.user;auditRole.value=log.role;auditDate.value=log.created_at;auditModule.value=log.module;auditAction.value=log.action;auditIp.value=log.ip;auditBrowser.value=log.browser;auditOs.value=log.os;auditDevice.value=log.device;auditSession.value=log.session_id;auditStatus.value=log.status;auditDescription.value=log.description;});});
})();
</script>
<?php require_once('includes/footer.php'); ?>