<?php require_once('includes/header.php'); ?>
<?php require_once('includes/cbt-data.php'); ?>
<?php require_once('includes/cbt-page-helper.php'); ?>
<?php require_once('includes/cbt-module-styles.php'); ?>
<?php
$cards = [
    ['title' => 'Total Exams', 'value' => count($cbtExams), 'description' => 'All CBT records', 'icon' => 'fa-laptop-file', 'color' => 'success'],
    ['title' => 'Active', 'value' => sms_cbt_count($cbtExams, 'status', 'Active'), 'description' => 'Available to students', 'icon' => 'fa-toggle-on', 'color' => 'success'],
    ['title' => 'Published', 'value' => sms_cbt_count($cbtExams, 'status', 'Published'), 'description' => 'Ready for activation', 'icon' => 'fa-bullhorn', 'color' => 'blue'],
    ['title' => 'Archived', 'value' => sms_cbt_count($cbtExams, 'status', 'Archived'), 'description' => 'Historical exams', 'icon' => 'fa-box-archive', 'color' => 'warning'],
];
$actions = ['View Exam','Edit Exam','Publish Exam','Activate Exam','Deactivate Exam','Archive Exam','Delete Exam'];
?>
<div class="admin-cbt-module">
    <section class="module-hero"><div class="breadcrumb-line">Dashboard <i class="fa-solid fa-angle-right mx-1"></i> CBT Management <i class="fa-solid fa-angle-right mx-1"></i> Exams</div><div class="d-flex align-items-center justify-content-between flex-wrap gap-3"><div><span class="module-kicker"><i class="fa-solid fa-laptop-file"></i> Exams</span><h3 class="mt-3 mb-2">CBT Exams</h3><p class="text-muted mb-0">Manage examinations, publication, activation, archival, deletion, and question previews.</p></div><button class="module-btn btn-primary-soft" data-bs-toggle="modal" data-bs-target="#examModal" type="button"><i class="fa-solid fa-plus"></i> Add Exam</button></div></section>
    <?php sms_cbt_render_cards($cards); ?>
    <section class="module-card"><h4>Search & Filter</h4><form class="cbt-filter-form"><div class="filter-grid"><div><label>Session</label><select class="form-select"><option>2025/2026</option><option>2026/2027</option></select></div><div><label>Term</label><select class="form-select"><option>First Term</option><option>Second Term</option><option>Third Term</option></select></div><div><label>Subject</label><select class="form-select"><option value="">All Subjects</option><?php foreach ($cbtSubjects as $subject): ?><option><?php echo sms_e($subject); ?></option><?php endforeach; ?></select></div><div><label>Class</label><select class="form-select"><option value="">All Classes</option><?php foreach ($cbtClasses as $class): ?><option><?php echo sms_e($class); ?></option><?php endforeach; ?></select></div><div><label>Teacher</label><input class="form-control" data-filter="search" placeholder="Search teacher or exam"></div><div><label>Status</label><select class="form-select" data-filter="status"><option value="">All Statuses</option><?php foreach ($cbtStatuses as $status): ?><option><?php echo sms_e($status); ?></option><?php endforeach; ?></select></div><div class="d-flex align-items-end gap-2"><button class="module-btn btn-primary-soft" type="submit">Search</button><button class="module-btn btn-muted-soft" type="reset">Reset</button></div></div></form></section>
    <section class="module-card"><div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3"><div><h4 class="mb-1">Exams Table</h4><p class="text-muted mb-0">Question preview is available in-page; no separate question bank is needed.</p></div><?php sms_cbt_render_exports(); ?></div><div class="table-shell"><table class="table cbt-table"><thead><tr><th>Exam Title</th><th>Subject</th><th>Teacher</th><th>Class</th><th>Duration</th><th>Questions</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($cbtExams as $exam): ?><tr data-status="<?php echo sms_e($exam['status']); ?>"><td><?php echo sms_e($exam['title']); ?></td><td><?php echo sms_e($exam['subject']); ?></td><td><?php echo sms_e($exam['teacher']); ?></td><td><?php echo sms_e($exam['class']); ?></td><td><?php echo sms_e($exam['duration']); ?></td><td><?php echo sms_e($exam['questions']); ?></td><td><?php echo sms_cbt_render_badge($exam['status']); ?></td><td><div class="dropdown"><button class="module-btn btn-muted-soft dropdown-toggle" data-bs-toggle="dropdown" type="button">Actions</button><div class="dropdown-menu dropdown-menu-end"><?php foreach ($actions as $action): ?><button class="dropdown-item <?php echo $action === 'View Exam' ? '' : 'cbt-action'; ?>" <?php echo $action === 'View Exam' ? 'data-bs-toggle="modal" data-bs-target="#questionPreviewModal"' : ''; ?> data-action="<?php echo sms_e($action); ?>" type="button"><i class="fa-solid <?php echo sms_e(sms_cbt_action_icon($action)); ?> me-2"></i><?php echo sms_e($action); ?></button><?php endforeach; ?></div></div></td></tr><?php endforeach; ?></tbody></table></div><?php sms_cbt_render_pagination(); ?></section>
    <div class="modal fade" id="questionPreviewModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Question Preview</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><?php foreach ($cbtQuestions as $question): ?><div class="module-card mb-3"><h5>Question <?php echo sms_e($question['number']); ?></h5><p class="fw-bold"><?php echo sms_e($question['question']); ?></p><div class="row g-2"><?php foreach ($question['options'] as $index => $option): ?><div class="col-sm-6"><div class="metric-row"><span><?php echo chr(65 + $index); ?>.</span><span><?php echo sms_e($option); ?></span></div></div><?php endforeach; ?></div><p class="mb-0 mt-2 text-muted fw-bold">Correct Answer: <?php echo sms_e($question['answer']); ?></p></div><?php endforeach; ?></div><div class="modal-footer"><button class="module-btn btn-muted-soft" data-bs-dismiss="modal" type="button">Close</button></div></div></div></div>
    <div class="modal fade" id="examModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><form class="modal-content" data-placeholder-form><div class="modal-header"><h5 class="modal-title">Add / Edit CBT Exam</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="form-grid"><div><label>Exam Title</label><input class="form-control" required></div><div><label>Subject</label><select class="form-select"><option>Mathematics</option></select></div><div><label>Class</label><select class="form-select"><option>SS 2 Science</option></select></div><div><label>Duration</label><input class="form-control" value="30 mins"></div><div class="full"><label>Instructions</label><textarea class="form-control"></textarea></div></div></div><div class="modal-footer"><button class="module-btn btn-muted-soft" data-bs-dismiss="modal" type="button">Cancel</button><button class="module-btn btn-primary-soft" type="submit">Save Exam</button></div></form></div></div>
</div></div></div>
<?php sms_cbt_render_common_script(); ?>
<?php require_once('includes/footer.php'); ?>