<?php require_once('includes/header.php'); ?>
<?php require_once('includes/teacher-data.php'); ?>
<?php $teacher = sms_admin_teacher_find($teacherRecords, sms_admin_teacher_selected_id()); ?>
<?php require_once('includes/teacher-module-styles.php'); ?>
<div class="admin-teacher-module">
    <section class="module-hero"><div class="breadcrumb-line">Dashboard <i class="fa-solid fa-angle-right mx-1"></i> Teacher Management <i class="fa-solid fa-angle-right mx-1"></i> Edit Teacher</div><div class="d-flex align-items-center justify-content-between flex-wrap gap-3"><div><span class="module-kicker"><i class="fa-solid fa-pen"></i> Edit Teacher</span><h3 class="mt-3 mb-2"><?php echo sms_e($teacher['full_name']); ?></h3><p class="text-muted mb-0">Update personal, contact, employment, qualification, assignment, and profile photo details using teacher_id <?php echo sms_e($teacher['teacher_id']); ?>.</p></div><a href="teacher-profile.php?teacher_id=<?php echo sms_e($teacher['teacher_id']); ?>" class="module-btn btn-outline-soft"><i class="fa-solid fa-id-card"></i> View Profile</a></div></section>
    <div id="saveAlert" class="alert-success-soft"><i class="fa-solid fa-circle-check me-2"></i>Teacher update validated and ready for database submission.</div>
    <form id="teacherEditForm" method="post" action="teacher-update.php" enctype="multipart/form-data">
        <input type="hidden" name="teacher_id" value="<?php echo sms_e($teacher['teacher_id']); ?>">
        <section class="module-card"><h4 class="mb-3">Personal & Contact Information</h4><div class="form-grid"><div class="full"><label>Profile Photo</label><input class="form-control" type="file" name="profile_photo" accept="image/*"></div><div><label>First Name</label><input class="form-control" name="first_name" value="<?php echo sms_e($teacher['first_name']); ?>" required></div><div><label>Middle Name</label><input class="form-control" name="middle_name" value="<?php echo sms_e($teacher['middle_name']); ?>"></div><div><label>Last Name</label><input class="form-control" name="last_name" value="<?php echo sms_e($teacher['last_name']); ?>" required></div><div><label>Gender</label><select class="form-select" name="gender"><option <?php echo $teacher['gender']==='Male'?'selected':''; ?>>Male</option><option <?php echo $teacher['gender']==='Female'?'selected':''; ?>>Female</option></select></div><div><label>Date of Birth</label><input class="form-control" type="date" name="date_of_birth" value="<?php echo sms_e($teacher['date_of_birth']); ?>"></div><div><label>Phone</label><input class="form-control" name="phone" value="<?php echo sms_e($teacher['phone']); ?>" required></div><div><label>Email</label><input class="form-control" type="email" name="email" value="<?php echo sms_e($teacher['email']); ?>" required></div><div class="full"><label>Address</label><textarea class="form-control" name="address"><?php echo sms_e($teacher['address']); ?></textarea></div></div></section>
        <section class="module-card"><h4 class="mb-3">Employment Information</h4><div class="form-grid"><div><label>Staff ID</label><input class="form-control" name="staff_id" value="<?php echo sms_e($teacher['staff_id']); ?>" readonly></div><div><label>Department</label><select class="form-select" name="department"><?php foreach ($teacherDepartments as $department): ?><option <?php echo $teacher['department']===$department?'selected':''; ?>><?php echo sms_e($department); ?></option><?php endforeach; ?></select></div><div><label>Designation</label><select class="form-select" name="designation"><?php foreach ($teacherDesignations as $designation): ?><option <?php echo $teacher['designation']===$designation?'selected':''; ?>><?php echo sms_e($designation); ?></option><?php endforeach; ?></select></div><div><label>Employment Date</label><input class="form-control" type="date" name="employment_date" value="<?php echo sms_e($teacher['employment_date']); ?>"></div><div><label>Employment Status</label><select class="form-select" name="employment_status"><?php foreach ($teacherStatuses as $status): ?><option <?php echo $teacher['status']===$status?'selected':''; ?>><?php echo sms_e($status); ?></option><?php endforeach; ?></select></div><div><label>Qualification</label><input class="form-control" name="qualification" value="<?php echo sms_e($teacher['qualification']); ?>"></div><div><label>Years of Experience</label><input class="form-control" type="number" min="0" name="experience" value="<?php echo sms_e($teacher['experience']); ?>"></div><div><label>Salary Grade</label><input class="form-control" name="salary_grade" value="<?php echo sms_e($teacher['salary_grade']); ?>"></div><div><label>Contract Type</label><select class="form-select" name="contract_type"><?php foreach ($contractTypes as $type): ?><option <?php echo $teacher['contract_type']===$type?'selected':''; ?>><?php echo sms_e($type); ?></option><?php endforeach; ?></select></div></div></section>
        <section class="module-card"><h4 class="mb-3">Assigned Subjects & Classes</h4><div class="form-grid two"><div class="multi-select-box"><label>Subjects</label><div class="multi-select-options"><?php foreach ($teacherSubjects as $subject): ?><label class="multi-option"><input class="form-check-input" type="checkbox" name="subjects[]" value="<?php echo sms_e($subject); ?>" <?php echo in_array($subject,$teacher['subjects'],true)?'checked':''; ?>> <?php echo sms_e($subject); ?></label><?php endforeach; ?></div></div><div class="multi-select-box"><label>Classes</label><div class="multi-select-options"><?php foreach ($teacherClasses as $class): ?><label class="multi-option"><input class="form-check-input" type="checkbox" name="classes[]" value="<?php echo sms_e($class); ?>" <?php echo in_array($class,$teacher['classes'],true)?'checked':''; ?>> <?php echo sms_e($class); ?></label><?php endforeach; ?></div></div></div></section>
        <section class="module-card"><div class="d-flex justify-content-end flex-wrap gap-2"><button class="module-btn btn-primary-soft" type="submit"><i class="fa-solid fa-floppy-disk"></i> Update Teacher</button><a class="module-btn btn-muted-soft" href="teachers.php">Cancel</a></div></section>
    </form>
</div></div></div>
<script>document.getElementById('teacherEditForm').addEventListener('submit',function(e){e.preventDefault(); if(!this.checkValidity()){this.reportValidity();return;} document.getElementById('saveAlert').style.display='block';});</script>
<?php require_once('includes/footer.php'); ?>