<?php require_once('includes/header.php'); ?>
<?php require_once('includes/timetable-data.php'); ?>
<?php require_once('includes/timetable-page-helper.php'); ?>
<?php require_once('includes/timetable-module-styles.php'); ?>
<?php
$cards = [
    ['title' => 'Opening Time', 'value' => '8:00 AM', 'description' => 'School day starts', 'icon' => 'fa-door-open', 'color' => 'success'],
    ['title' => 'Closing Time', 'value' => '3:00 PM', 'description' => 'School day ends', 'icon' => 'fa-door-closed', 'color' => 'blue'],
    ['title' => 'Periods Per Day', 'value' => $timetableSettings['periods_per_day'], 'description' => 'Default daily periods', 'icon' => 'fa-list-ol', 'color' => 'warning'],
    ['title' => 'Conflict Detection', 'value' => $timetableSettings['enable_conflict_detection'] ? 'On' : 'Off', 'description' => 'Overlap protection', 'icon' => 'fa-shield-halved', 'color' => 'success'],
];
$weekDays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
?>
<div class="admin-timetable-module">
    <section class="module-hero"><div class="breadcrumb-line">Dashboard <i class="fa-solid fa-angle-right mx-1"></i> Timetable Management <i class="fa-solid fa-angle-right mx-1"></i> Timetable Settings</div><div class="d-flex align-items-center justify-content-between flex-wrap gap-3"><div><span class="module-kicker"><i class="fa-solid fa-gears"></i> Timetable Settings</span><h3 class="mt-3 mb-2">Timetable Settings</h3><p class="text-muted mb-0">Configure global school hours, working days, periods, breaks, venues, and scheduling rules.</p></div><button class="module-btn btn-primary-soft" form="timetableSettingsForm" type="submit"><i class="fa-solid fa-floppy-disk"></i> Save Changes</button></div></section>
    <?php sms_timetable_render_cards($cards); ?>
    <form id="timetableSettingsForm" data-placeholder-form>
        <section class="module-card"><h4>School Hours</h4><div class="filter-grid"><div><label>School Opening Time</label><input class="form-control" type="time" value="<?php echo sms_e($timetableSettings['opening_time']); ?>"></div><div><label>School Closing Time</label><input class="form-control" type="time" value="<?php echo sms_e($timetableSettings['closing_time']); ?>"></div><div><label>Default Lesson Duration</label><input class="form-control" type="number" value="<?php echo sms_e($timetableSettings['default_lesson_duration']); ?>"></div><div><label>Break Duration</label><input class="form-control" type="number" value="<?php echo sms_e($timetableSettings['break_duration']); ?>"></div><div><label>Number of Periods Per Day</label><input class="form-control" type="number" value="<?php echo sms_e($timetableSettings['periods_per_day']); ?>"></div></div></section>
        <section class="module-card"><h4>Working Days</h4><div class="row g-3 mt-1"><?php foreach ($weekDays as $index => $day): ?><div class="col-sm-6 col-xl-3"><label class="day-toggle"><span><?php echo sms_e($day); ?></span><input class="form-check-input" type="checkbox" <?php echo $index < 5 ? 'checked' : ''; ?>></label></div><?php endforeach; ?></div></section>
        <section class="module-card"><div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3"><div><h4 class="mb-1">Default Time Slots</h4><p class="text-muted mb-0">Edit school lesson periods and break slots.</p></div><button class="module-btn btn-primary-soft" data-bs-toggle="modal" data-bs-target="#periodModal" type="button"><i class="fa-solid fa-plus"></i> Add Period</button></div><div class="table-shell"><table class="table"><thead><tr><th>Period</th><th>Start</th><th>End</th><th>Actions</th></tr></thead><tbody><?php foreach ($timetablePeriods as $period): ?><tr><td><?php echo sms_e($period['period']); ?></td><td><?php echo sms_e($period['start']); ?></td><td><?php echo sms_e($period['end']); ?></td><td><div class="d-flex gap-1"><button class="action-btn" data-bs-toggle="modal" data-bs-target="#periodModal" type="button" title="Edit Period"><i class="fa-solid fa-pen"></i></button><button class="action-btn tt-action" data-action="Delete" type="button" title="Delete Period"><i class="fa-solid fa-trash"></i></button></div></td></tr><?php endforeach; ?></tbody></table></div></section>
        <section class="module-card"><h4>General Settings</h4><div class="filter-grid"><div><label>Enable Conflict Detection</label><select class="form-select"><option selected>Enabled</option><option>Disabled</option></select></div><div><label>Allow Double Periods</label><select class="form-select"><option selected>Enabled</option><option>Disabled</option></select></div><div><label>Auto Assign Break Time</label><select class="form-select"><option selected>Enabled</option><option>Disabled</option></select></div><div><label>Default Venue</label><select class="form-select"><option value="">Optional</option><?php foreach ($timetableVenues as $venue): ?><option <?php echo $venue['name'] === $timetableSettings['default_venue'] ? 'selected' : ''; ?> value="<?php echo sms_e($venue['id']); ?>"><?php echo sms_e($venue['name']); ?></option><?php endforeach; ?></select></div><div class="d-flex align-items-end gap-2"><button class="module-btn btn-primary-soft" type="submit">Save Changes</button><button class="module-btn btn-muted-soft" type="reset">Reset to Default</button></div></div></section>
    </form>
    <div class="modal fade" id="periodModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" data-placeholder-form><div class="modal-header"><h5 class="modal-title">Add / Edit Period</h5><button class="btn-close" data-bs-dismiss="modal" type="button"></button></div><div class="modal-body"><p class="text-muted fw-bold">Future backend logic should persist this to school_periods and validate period overlaps.</p><div class="form-grid"><div><label>Period Name</label><input class="form-control" required placeholder="Period 1"></div><div><label>Start</label><input class="form-control" type="time" required></div><div><label>End</label><input class="form-control" type="time" required></div></div></div><div class="modal-footer"><button class="module-btn btn-muted-soft" data-bs-dismiss="modal" type="button">Cancel</button><button class="module-btn btn-primary-soft" type="submit">Save Period</button></div></form></div></div>
</div></div></div>
<?php sms_timetable_common_script(); ?>
<?php require_once('includes/footer.php'); ?>